package General;

/**
 *
 * @author Cesar Programacion
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmuCatalogo = new javax.swing.JMenu();
        jmuArturo = new javax.swing.JMenu();
        jmuAdam = new javax.swing.JMenu();
        jmuIsai = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmuCatalogo.setText("Catàlogo");

        jmuArturo.setText("Arturo");
        jmuCatalogo.add(jmuArturo);

        jmuAdam.setText("Adam");
        jmuCatalogo.add(jmuAdam);

        jmuIsai.setText("Isaì");
        jmuCatalogo.add(jmuIsai);

        jMenuBar1.add(jmuCatalogo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmuAdam;
    private javax.swing.JMenu jmuArturo;
    private javax.swing.JMenu jmuCatalogo;
    private javax.swing.JMenu jmuIsai;
    // End of variables declaration//GEN-END:variables
}
